# App 
server:
  servlet:
    application-display-name: 
    context-path: 

# Jackson
spring:
  jackson:
    default-property-inclusion: non_null 

# JPA
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl