# App 
server:
  servlet:
    application-display-name: Donatio
    context-path: /donatio

# Jackson
spring:
  jackson:
    default-property-inclusion: non_null 

# JPA
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: 'root'
    password: '@braTe07'
    url: jdbc:mysql://localhost:3306/db_donatio